spring.application.name=EcoRecycle

#Server configuration
server.port=8080

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/EcoRecycleDB
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true

#Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
